# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://35.232.111.65:80/echo
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU0NjcwNTA0NiwiZXhwIjoxNTQ2NzkxNDQ2LCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.LzV1ey815If8YJFfntLVjMSdef4drLMPHVIwOwO9yIe3fz2GoVGPn_Mjs_AwGKIQF0tsW7qWgJtowT74DuIRv4bYtKKXEJ3wuEBTsWMForh2r_t7O2luIrOWrNH0piOyGBT17b7x4Q6sCdn8mkthPySd0K1f9ROSdsxq7hDnjtZn8AKYN814kIF1LZotZEOEIJGt6teI9JlvX6JBeYVGIg4sqw7yNfo1R4qsbm2BRIAJn0UOmsFGxs6OkLgqG7YJslgzKbCDVw7rdRoBQrqJc8zDbbnQtu1kzhXHb0ZNLQrt2Tq5cFm_6KDowFLYUiifxL23IxuYV81dTgP8ajNTDA

{ "message": "Hello World Michael" }

###

POST http://localhost:8082/product
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU0OTQ4MzQzNSwiZXhwIjoxNTQ5NTY5ODM1LCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.WwwXVHNiX0a0PnpNYLj2ey6Rt-orK9g6RKw-839uSYvUmz8e9jDaeyUMRAi7HHm292CRB9Bv_5KdycD_oVoa0ufPZlpflJdkpWm453xqiGTpUOzOdhTCw1chxNNxMN1FRF2f5F2GpgKofxSdMDcQC--sGogrgfnFNcr8LPHfChHaoBxcXwi3QIEupnBgpNuM0oJ43zOjwKU1ccOd-DHsAA6wAsWtzJmPYRv0xg0rAqPq_x72q8IJr7He-6wj9o6MOstrN3XZKARAmtLzV0C8VtkGyCYs88fcdla6rsPDd2CHoEjlWHnO7rgUVhLED8Ss3M6_VjHlVcK4iglgLaXXqQ

{  "productCode": "prod17", "shortDesc": "Short desc for prod 17", "longDesc": "Long desc for prod 17" }

###

POST http://localhost:8080/product
Accept: application/json

{  "productCode": "prod18", "shortDesc": "Short desc for prod 18", "longDesc": "Long desc for prod 18" }

###

PUT http://localhost:8080/product
Accept: application/json

{ "productId": "15", "productCode": "prod15", "shortDesc": "Shortest description for prod 15", "longDesc": "Longest desc for prod 15" }

###

GET http://localhost:8080/product/15
Accept: application/json

###

GET http://localhost:8080/products
Accept: application/json

###

GET http://localhost:8082/products
Accept: application/json

###

DELETE http://localhost:8080/product/16
Accept: application/json

###

GET http://localhost:8080
Accept: application/json

###

GET http://localhost:8080/error
Accept: application/json

###

GET http://localhost:8080/fatal
Accept: application/json

###

GET http://35.232.93.44/products
Accept: application/json

###

GET http://35.232.93.44/product/22
Accept: application/json

###

POST http://35.232.93.44/product
Accept: application/json

{  "productCode": "prodqwqw", "shortDesc": "Short desc for prod 8", "longDesc": "Long desc for prod 8" }

###

DELETE http://35.232.93.44/product/16
Accept: application/json

###
