# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/product
Accept: application/json

{  "productCode": "prod0000", "shortDesc": "Short desc for prod 6", "longDesc": "Long desc for prod 6" }

###

GET http://localhost:8080/product/10
Accept: application/json

###

GET http://localhost:8080/product
Accept: application/json

###

DELETE http://localhost:8080/product/11
Accept: application/json

###

GET http://localhost:8080
Accept: application/json

###

GET http://localhost:8080/error
Accept: application/json

###

GET http://localhost:8080/fatal
Accept: application/json

###

GET http://35.232.93.44/product
Accept: application/json

###

GET http://35.232.93.44/product/20
Accept: application/json

###

POST http://35.232.93.44/product
Accept: application/json

{  "productCode": "prod94949", "shortDesc": "Short desc for prod 5", "longDesc": "Long desc for prod 5" }

###

GET http://146.148.43.51/error
Accept: application/json

###

GET http://localhost:6060/foo

###

GET http://localhost:8080/hello

###
