# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://35.232.111.65:80/echo
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU0NjcwNTA0NiwiZXhwIjoxNTQ2NzkxNDQ2LCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.LzV1ey815If8YJFfntLVjMSdef4drLMPHVIwOwO9yIe3fz2GoVGPn_Mjs_AwGKIQF0tsW7qWgJtowT74DuIRv4bYtKKXEJ3wuEBTsWMForh2r_t7O2luIrOWrNH0piOyGBT17b7x4Q6sCdn8mkthPySd0K1f9ROSdsxq7hDnjtZn8AKYN814kIF1LZotZEOEIJGt6teI9JlvX6JBeYVGIg4sqw7yNfo1R4qsbm2BRIAJn0UOmsFGxs6OkLgqG7YJslgzKbCDVw7rdRoBQrqJc8zDbbnQtu1kzhXHb0ZNLQrt2Tq5cFm_6KDowFLYUiifxL23IxuYV81dTgP8ajNTDA

{ "message": "Hello World Michael" }

###

POST http://localhost:8082/product
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU1MDQ0Mjc5MywiZXhwIjoxNTUwNTI5MTkzLCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.nUKHE55Wq5erJajayqf35bs6hldens7b0RpzoKCYSa6_2Ljzea4QDU3ZoLGB8JK0BOt_oBzIUQEHlPtRumSfjWAii2sNFw0OLVzL6xrtKYLfmFWhxmZrtj8Ew_Xu0kY651oi_iqk62DPHLppakRMynP3SJULMxIBRWkVyyCzspHJiJ2LE2wi7IzhceKt-eECophrIVadWszw5x3nIFTc6_R7pq5DvXLQL4i5_tiCnuOFdmbpn01a729EV2dhx8sHKA2bXzKh82P5RGPiRNhPQ4lBpr1hLRqEYm7Hxt3et1TQRyg-Z-hTfHK_Yl5iW_4qzmJqlL7FqvuyBxtClYVt8w

{  "productCode": "prod19", "shortDesc": "Short desc for prod 19", "longDesc": "Long desc for prod 19" }

###

POST http://localhost:8080/product
Accept: application/json

{  "productCode": "prod18", "shortDesc": "Short desc for prod 18", "longDesc": "Long desc for prod 18" }

###

POST http://localhost:8080/timesheets
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6InF4WUpjbGlSdzFhSmdmWnZ3Zll4OU1CMVlhcjBGNDJHQGNsaWVudHMiLCJhdWQiOiJodHRwczovL2FwaS5leGFtcGxlY28uY29tL3RpbWVzaGVldHMiLCJpYXQiOjE1NTEwNDgzMjUsImV4cCI6MTU1MTEzNDcyNSwiYXpwIjoicXhZSmNsaVJ3MWFKZ2ZadndmWXg5TUIxWWFyMEY0MkciLCJzY29wZSI6ImNyZWF0ZTp0aW1lc2hlZXRzIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.pqGtqRoJudTNc6AZJPqi3ww3JtBNRL8IC5d_ivE5Pkhnp5Sr9KVdMGtxs2qvJyqZCeoJKn1xNHr0cl-JfuLnnlvJkRQKCSrBc06dhXjdY4sAzL22syPNf_6_8VhomBZb1_iOZnXYakndvYUpa88q9oWtgIOGz9ArgD8en2d8XWePKPvo4g6nuvs6OTw3J-aDnd9VQGpF_cn0ttlZAqGH15wnYQTDf_YQPI-Dfpy0iABUTn5xS0jJAbCPCgJjfiyWYmODpLqEdbdel1RNS_l6zUTmk_pj5GjekZ2oF8rAJc403mLTKXfqVadO0EDd51D4HQPfG6C1fiXyPKC7ec2yCA

{
	"user_type": "Employee",
	"user_id": "007",
	"year": 2016,
	"week": 24,
	"project": "StoreZero",
	"hours": 40
}

###

PUT http://localhost:8080/product
Accept: application/json

{ "productId": "15", "productCode": "prod15", "shortDesc": "Shortest description for prod 15", "longDesc": "Longest desc for prod 15" }

###

PUT http://localhost:8082/product
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU1MDQ0Mjc5MywiZXhwIjoxNTUwNTI5MTkzLCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.nUKHE55Wq5erJajayqf35bs6hldens7b0RpzoKCYSa6_2Ljzea4QDU3ZoLGB8JK0BOt_oBzIUQEHlPtRumSfjWAii2sNFw0OLVzL6xrtKYLfmFWhxmZrtj8Ew_Xu0kY651oi_iqk62DPHLppakRMynP3SJULMxIBRWkVyyCzspHJiJ2LE2wi7IzhceKt-eECophrIVadWszw5x3nIFTc6_R7pq5DvXLQL4i5_tiCnuOFdmbpn01a729EV2dhx8sHKA2bXzKh82P5RGPiRNhPQ4lBpr1hLRqEYm7Hxt3et1TQRyg-Z-hTfHK_Yl5iW_4qzmJqlL7FqvuyBxtClYVt8w

{ "productId": "20", "productCode": "prod19", "shortDesc": "Shortest description for prod 19", "longDesc": "Longest desc for prod 19" }

###

GET http://localhost:8080/product/15
Accept: application/json

###

GET http://localhost:8080/products
Accept: application/json

###

GET https://geauxcommerce.auth0.com/userinfo
Accept: application/json
Authorization: Bearer 7PeI2lOj_lI2Hf6zh25rBymVtrmalzAv

###

GET http://localhost:8082/product/15
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6IlZOT1pRRHhod1NWUTRBRGlRZXBhT2hWeFBXcUNmbmR1QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU1MDU4MTQ1MiwiZXhwIjoxNTUwNjY3ODUyLCJhenAiOiJWTk9aUUR4aHdTVlE0QURpUWVwYU9oVnhQV3FDZm5kdSIsInNjb3BlIjoid3JpdGU6cHJvZHVjdCByZWFkOnByb2R1Y3QiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.C8OxCR8eZE7bDrcRPXMEZTuYZrRCMlRQnh-GtKx68mPhrbbuM9U-a3QVjM0Pj1r4-0-UUl2VwacCYfdGZdAHPNlRrvXKf55eWsf5Bshkf2jruR3gQrksEBWIHlSNjM3UJd3yBQJYOl52CYHSnjk-bgkxNncKW03UizglLofO4whE6JrnNVrl7q6KatgyzjE8Asxepi79FnKsjGipPaDUGcqAfYgTZkqoVz3Plb4lYAmNTzxvXXNPabW3dZofD1rHVhlIWXnuJRSNMga1eFLqipFVOAuhjLsueeQMdrKyocu-8WXyb_7cshfNZmxDeWdS0kqfEVZZ4LHFXIGWZ2ioVg

###

GET http://localhost:8082/products
Accept: application/json

###

DELETE http://localhost:8080/product/16
Accept: application/json

###

DELETE http://localhost:8082/product/17
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJrUTRPVFEzTVRVeVEwWTRPREk1TlVRd1JVRXhSRE5GUmtSQlFrWkdNVVEzTkRnME0wVkJOQSJ9.eyJpc3MiOiJodHRwczovL2dlYXV4Y29tbWVyY2UuYXV0aDAuY29tLyIsInN1YiI6ImRZQmdEY3dnNFpSam5yaHN6RXJ0bGViSU5ieVM5akM4QGNsaWVudHMiLCJhdWQiOiJodHRwOi8vZ29vZ2xlX2FwaSIsImlhdCI6MTU1MDQ0Mjc5MywiZXhwIjoxNTUwNTI5MTkzLCJhenAiOiJkWUJnRGN3ZzRaUmpucmhzekVydGxlYklOYnlTOWpDOCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.nUKHE55Wq5erJajayqf35bs6hldens7b0RpzoKCYSa6_2Ljzea4QDU3ZoLGB8JK0BOt_oBzIUQEHlPtRumSfjWAii2sNFw0OLVzL6xrtKYLfmFWhxmZrtj8Ew_Xu0kY651oi_iqk62DPHLppakRMynP3SJULMxIBRWkVyyCzspHJiJ2LE2wi7IzhceKt-eECophrIVadWszw5x3nIFTc6_R7pq5DvXLQL4i5_tiCnuOFdmbpn01a729EV2dhx8sHKA2bXzKh82P5RGPiRNhPQ4lBpr1hLRqEYm7Hxt3et1TQRyg-Z-hTfHK_Yl5iW_4qzmJqlL7FqvuyBxtClYVt8w

###

GET http://localhost:8080
Accept: application/json

###

GET http://localhost:8080/error
Accept: application/json

###

GET http://localhost:8080/fatal
Accept: application/json

###

GET http://35.232.93.44/products
Accept: application/json

###

GET http://35.232.93.44/product/22
Accept: application/json

###

POST http://35.232.93.44/product
Accept: application/json

{  "productCode": "prodqwqw", "shortDesc": "Short desc for prod 8", "longDesc": "Long desc for prod 8" }

###

DELETE http://35.232.93.44/product/16
Accept: application/json

###
