---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "catalog-frontend-service"
  namespace: "default"
  labels:
    app: "catalog-frontend"
    tier: "frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "catalog-frontend"
    tier: "frontend"
  type: "LoadBalancer"
  loadBalancerIP: ""
