---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "catalog-frontend"
  namespace: "default"
  labels:
    app: "catalog-frontend"
    tier: "frontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "catalog-frontend"
      tier: "frontend"
  template:
    metadata:
      labels:
        app: "catalog-frontend"
        tier: "frontend"
    spec:
      containers:
      - name: "catalog"
        image: "gcr.io/demogeauxcommerce/catalog:master"
        env:
        - name: MYSQL_DB_HOST
          value: 127.0.0.1:3306
        - name: USE_STACKDRIVER
          value: TRUE
        # These secrets are required to start the pod.
        # [START cloudsql_secrets]
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password

      # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
      # project, the region of your Cloud SQL instance and the name
      # of your Cloud SQL instance. The format is
      # $PROJECT:$REGION:$INSTANCE
      # [START proxy_container]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=demogeauxcommerce:us-central1:catalog-mysql=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      # [END proxy_container]
      # [START volumes]
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      # [END volumes]

---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "catalog-frontend-hpa"
  namespace: "default"
  labels:
    app: "catalog-frontend"
    tier: "frontend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "catalog-frontend"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
